-- =====================================================
-- Estrutural: role platform_owner + auditoria permanente
-- Nao executa automaticamente. Revisar antes de aplicar.
-- =====================================================

-- 1) Tabela de auditoria
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  usuario_id uuid,
  usuario_nome text,
  usuario_email text,
  usuario_role text,
  acao text not null,
  entidade text not null,
  entidade_id text,
  evento_id bigint,
  lista_id bigint,
  participante_id bigint,
  descricao text,
  dados_anteriores jsonb,
  dados_novos jsonb,
  ip text,
  user_agent text
);

create index if not exists idx_audit_logs_created_at on public.audit_logs (created_at desc);
create index if not exists idx_audit_logs_usuario_id on public.audit_logs (usuario_id);
create index if not exists idx_audit_logs_acao on public.audit_logs (acao);
create index if not exists idx_audit_logs_entidade on public.audit_logs (entidade);
create index if not exists idx_audit_logs_evento_id on public.audit_logs (evento_id);
create index if not exists idx_audit_logs_lista_id on public.audit_logs (lista_id);
create index if not exists idx_audit_logs_participante_id on public.audit_logs (participante_id);

-- 2) RLS: leitura global apenas para platform_owner
alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_select_platform_owner on public.audit_logs;
create policy audit_logs_select_platform_owner
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.usuarios u
    where u.id = auth.uid()
      and u.role = 'platform_owner'
  )
);

-- Sem policy de update/delete/insert para authenticated.
-- INSERT da aplicacao deve ser server-side (service role) ou via funcao SECURITY DEFINER.

-- 3) Funcoes utilitarias de auditoria
create or replace function public.fn_audit_actor()
returns table (
  p_usuario_id uuid,
  p_usuario_nome text,
  p_usuario_email text,
  p_usuario_role text
)
language sql
security definer
set search_path = public
as $$
  select
    u.id,
    u.nome,
    u.email,
    u.role
  from public.usuarios u
  where u.id = auth.uid();
$$;

create or replace function public.fn_audit_insert(
  p_acao text,
  p_entidade text,
  p_entidade_id text default null,
  p_evento_id bigint default null,
  p_lista_id bigint default null,
  p_participante_id bigint default null,
  p_descricao text default null,
  p_dados_anteriores jsonb default null,
  p_dados_novos jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor record;
begin
  select * into v_actor from public.fn_audit_actor() limit 1;

  insert into public.audit_logs (
    usuario_id,
    usuario_nome,
    usuario_email,
    usuario_role,
    acao,
    entidade,
    entidade_id,
    evento_id,
    lista_id,
    participante_id,
    descricao,
    dados_anteriores,
    dados_novos
  )
  values (
    v_actor.p_usuario_id,
    v_actor.p_usuario_nome,
    v_actor.p_usuario_email,
    v_actor.p_usuario_role,
    p_acao,
    p_entidade,
    p_entidade_id,
    p_evento_id,
    p_lista_id,
    p_participante_id,
    p_descricao,
    p_dados_anteriores,
    p_dados_novos
  );
end;
$$;

-- 4) Triggers para eventos
create or replace function public.fn_audit_eventos()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.fn_audit_insert(
      'evento_criado',
      'evento',
      new.id::text,
      new.id,
      null,
      null,
      format('Criou o evento %s.', coalesce(new.nome, 'Sem nome')),
      null,
      to_jsonb(new)
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    perform public.fn_audit_insert(
      'evento_editado',
      'evento',
      new.id::text,
      new.id,
      null,
      null,
      format('Editou o evento %s.', coalesce(new.nome, old.nome, 'Sem nome')),
      to_jsonb(old),
      to_jsonb(new)
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.fn_audit_insert(
      'evento_excluido',
      'evento',
      old.id::text,
      old.id,
      null,
      null,
      format('Excluiu o evento %s.', coalesce(old.nome, 'Sem nome')),
      to_jsonb(old),
      null
    );
    return old;
  end if;

  return null;
end;
$$;

-- 5) Triggers para listas
create or replace function public.fn_audit_listas_evento()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nome_evento text;
  v_acao text;
  v_descricao text;
begin
  if tg_op in ('INSERT', 'UPDATE') then
    select e.nome into v_nome_evento from public.eventos e where e.id = new.evento_id;
  else
    select e.nome into v_nome_evento from public.eventos e where e.id = old.evento_id;
  end if;

  if tg_op = 'INSERT' then
    v_acao := 'lista_criada';
    v_descricao := format('Criou a lista %s no evento %s.', coalesce(new.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome'));

    perform public.fn_audit_insert(
      v_acao,
      'lista',
      new.id::text,
      new.evento_id,
      new.id,
      null,
      v_descricao,
      null,
      to_jsonb(new)
    );

    return new;
  end if;

  if tg_op = 'UPDATE' then
    if coalesce(old.tipo_visibilidade, old.visibilidade, '') is distinct from coalesce(new.tipo_visibilidade, new.visibilidade, '') then
      v_acao := 'lista_visibilidade_alterada';
      v_descricao := format('Alterou a visibilidade da lista %s no evento %s.', coalesce(new.nome, old.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome'));
    elsif coalesce(old.meta_pixel_id, '') is distinct from coalesce(new.meta_pixel_id, '') then
      v_acao := 'lista_pixel_alterado';
      v_descricao := format('Alterou o Pixel da lista %s no evento %s.', coalesce(new.nome, old.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome'));
    else
      v_acao := 'lista_editada';
      v_descricao := format('Editou a lista %s no evento %s.', coalesce(new.nome, old.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome'));
    end if;

    perform public.fn_audit_insert(
      v_acao,
      'lista',
      new.id::text,
      new.evento_id,
      new.id,
      null,
      v_descricao,
      to_jsonb(old),
      to_jsonb(new)
    );

    return new;
  end if;

  if tg_op = 'DELETE' then
    v_acao := 'lista_excluida';
    v_descricao := format('Excluiu a lista %s no evento %s.', coalesce(old.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome'));

    perform public.fn_audit_insert(
      v_acao,
      'lista',
      old.id::text,
      old.evento_id,
      old.id,
      null,
      v_descricao,
      to_jsonb(old),
      null
    );

    return old;
  end if;

  return null;
end;
$$;

-- 6) Triggers para participantes
create or replace function public.fn_audit_participantes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nome_evento text;
begin
  if tg_op in ('INSERT', 'UPDATE') then
    select e.nome into v_nome_evento from public.eventos e where e.id = new.evento_id;
  else
    select e.nome into v_nome_evento from public.eventos e where e.id = old.evento_id;
  end if;

  if tg_op = 'INSERT' then
    perform public.fn_audit_insert(
      'participante_adicionado',
      'participante',
      new.id::text,
      new.evento_id,
      new.lista_id,
      new.id,
      format('Adicionou o participante %s no evento %s.', coalesce(new.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome')),
      null,
      to_jsonb(new)
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    -- Evita duplicidade no check-in quando ja existir log via camada de aplicacao.
    if (
      coalesce(old.presente, false) is distinct from coalesce(new.presente, false)
      and old.nome is not distinct from new.nome
      and old.lista_id is not distinct from new.lista_id
      and old.evento_id is not distinct from new.evento_id
    ) then
      return new;
    end if;

    perform public.fn_audit_insert(
      'participante_editado',
      'participante',
      new.id::text,
      new.evento_id,
      new.lista_id,
      new.id,
      format('Editou o participante %s no evento %s.', coalesce(new.nome, old.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome')),
      to_jsonb(old),
      to_jsonb(new)
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.fn_audit_insert(
      'participante_excluido',
      'participante',
      old.id::text,
      old.evento_id,
      old.lista_id,
      old.id,
      format('Excluiu o participante %s do evento %s.', coalesce(old.nome, 'Sem nome'), coalesce(v_nome_evento, 'Sem nome')),
      to_jsonb(old),
      null
    );
    return old;
  end if;

  return null;
end;
$$;

-- 7) Instalacao dos triggers

drop trigger if exists trg_audit_eventos on public.eventos;
create trigger trg_audit_eventos
after insert or update or delete on public.eventos
for each row execute function public.fn_audit_eventos();

drop trigger if exists trg_audit_listas_evento on public.listas_evento;
create trigger trg_audit_listas_evento
after insert or update or delete on public.listas_evento
for each row execute function public.fn_audit_listas_evento();

drop trigger if exists trg_audit_participantes on public.participantes;
create trigger trg_audit_participantes
after insert or update or delete on public.participantes
for each row execute function public.fn_audit_participantes();

-- Observacao: acoes de usuario (criacao/edicao/role/senha/exclusao) e check-in
-- ja possuem registro pela camada server-side em API routes.
