-- =====================================================
-- SPRINT 4.0 - Equipe do Evento
-- Tabela de vinculo de staff por evento
-- =====================================================

create table if not exists public.evento_staff (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos (id) on delete cascade,
  usuario_id uuid not null references public.usuarios (id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_evento_staff_evento_usuario_unique
  on public.evento_staff (evento_id, usuario_id);

create index if not exists idx_evento_staff_evento_id
  on public.evento_staff (evento_id);

create index if not exists idx_evento_staff_usuario_id
  on public.evento_staff (usuario_id);
